jobs:
  - ${{ each image in parameters.images }}:
      - job:

        displayName: ${{image.displayName}}
        
        pool:
          vmImage: ${{image.vmImage}}
        
        variables:
          currentImage: ${{image.vmImage}}
          JAVA_TOOL_OPTIONS: ${{image.javaToolOptions}}

        steps:
          # Runs 'mvn clean install'
          - task: Maven@4
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m -Dmaven.resolver.transport=wagon'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '${{image.jdkVersion}}'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/TEST-*.xml'
              goals: 'clean build'